### ISSUE TITLE
Rename too generic global types/vars

### ISSUE THREAD

**Issue by Alexey-T** [zsoltszakaly/getoptionsforpascal#1]
```
type
  // Basic types derived from standard pascal types
  pInteger = ^Integer;
  tChars = array of Char;
  tStrings = array of string;

  // Enumerated types used when the function is called
  tArgumentOptions     = (aoMandatory, aoOptional, aoNotAllowed);
      // (the names are self explanatory)
  tSortingOptions      = (soDefinition, soReturnValue, soInput, soClassic);
      // Sets the sequence in the result:
      //   soDefinition  : in the order how the given option was defined
      //   soReturnValue : in the order of the return value of the option
      //   soInput       : in the same order, including Non-Options, as the user input them
      //   soClassic     : in the same order as the user input the options and then followed by the Non-Options also in input order

```
Its interface section. too generic names may give conflict in big projects!

**Comment by Alexey-T** [comment]
Pls give some prefix, like "go_" or "getopt_".

**Comment by Alexey-T** [comment]
And for this func too
```
// The main function
function CommandLineParameters(const aOptions : tOptionDefinitions; aSorting : tSortingOptions = soClassic) :
    tOptionResults;
```

**Comment by zsoltszakaly** [comment]
In case of pInteger I agree. It is so generic that actually it is system defined and so, I removed.
For the rest I am not convinced:
- tChars, tStrings are not system defined, but according to the normal Pascal logic, elsewhere it would be defined the same way.
- tArgumentOptions and tSortingOptions are not that generic and not used elsewhere. Google has zero hit for the first and 1 hit for the second.
- CommandLineParameters is the most descriptive name of the function, what I would really be surprised to see in conflict with another such named function within one project (why would one want to use two function with the same purpose?).
- And last, but not least, the most important reason why I do not agree, is that in Pascal we can always use the unit name as a namespace. The most classic example is Close. Using GUI libraries Close is typically to close a form, window, etc. If you want to use the basic file operator close, you simply have to use system.close and the conflict is solved. So in the rare case one would have another CommandLineParameters function and that would be defined later, while the purpose is to call this one, it is simple getoptions.CommandLineParameters. I think it is more elegant to use, than for a rare case make the name a more ugly go_CommandLineParameters.
